### PR TITLE
Avoid attempting to sync with disconnected peers

### LINKED ISSUE #5643: Aleth tries to sync with peer after status verification fails
Take node `2124182c…` in the following log snippet:

```
DEBUG 06-29 14:58:52 p2p  ethcap Status (from ##2124182c…): 63 / 1 / #82270b80…, TD: 44733633866011995653 = #b41213a3…
DEBUG 06-29 14:58:52 p2p  sync   Peer ##2124182c… not suitable for sync: Genesis hash mismatch. Host genesis hash: d4e56740…, peer genesis hash: 82270b80…
TRACE 06-29 14:58:52 p2p  net    Disconnecting (our reason: Peer had no use for this node.) from (##2124182c…@54.39.102.75:30005)
TRACE 06-29 14:58:52 p2p  net    Disconnect to (##2124182c…@54.39.102.75:30005)
TRACE 06-29 14:58:52 p2p  net    Closing (Peer had no use for this node.) connection with (##2124182c…@54.39.102.75:30005)
TRACE 06-29 14:58:52 p2p  net    Received Disconnect (1) from (##3440a67b…@206.189.205.173:30303)
TRACE 06-29 14:58:52 p2p  p2pcap Disconnect from (##3440a67b…@206.189.205.173:30303)
DEBUG 06-29 14:58:52 p2p  p2pcap Disconnect (reason: Peer had too many connections.) from (##3440a67b…@206.189.205.173:30303)
TRACE 06-29 14:58:52 p2p  net    Closing (Disconnect was requested.) connection with (##3440a67b…@206.189.205.173:30303)
DEBUG 06-29 14:58:52 p2p  net    Closing peer session with (##3440a67b…@206.189.205.173:30303)
DEBUG 06-29 14:58:52 p2p  sync   Discovered new highest difficulty (44733633866011995653) from peer ##2124182c…
INFO  06-29 14:58:52 p2p  sync   Starting full sync
DEBUG 06-29 14:58:52 p2p  sync   Syncing with peer ##2124182c…
DEBUG 06-29 14:58:52 p2p  peer   Requesting 1 block headers starting from #b41213a3… from ##2124182c… 2124182c…
TRACE 06-29 14:58:52 p2p  net    GetBlockHeaders to (##2124182c…@54.39.102.75:30005)
TRACE 06-29 14:58:52 p2p  net    Starting RLPX handshake with ##2e7d35b9…@18.162.59.149:3332
DEBUG 06-29 14:58:52 p2p  net    Closing peer session with (##2124182c…@54.39.102.75:30005)
TRACE 06-29 14:58:52 p2p  net    Starting RLPX handshake with ##85d95b32…@18.228.30.92:21000
DEBUG 06-29 14:58:52 p2p  net    Starting peer session with giov/v0.0.6-unstable/linux-amd64/go1.11.5 (protocol: V5) ##4223300e… capabilities: (eth,63) port: 0
DEBUG 06-29 14:58:52 p2p  net    New session for capability eth; idOffset: 16 with ##4223300e…@47.245.30.101:30303
TRACE 06-29 14:58:52 p2p  net    Status to (##4223300e…@47.245.30.101:30303)
```

Log breakdown: 

1. Aleth determines that the node can't be sync'd with since it's on a different chain so it sends a disconnect p2p capability packet to the node and closes its session:

```
DEBUG 06-29 14:58:52 p2p  sync   Peer ##2124182c… not suitable for sync: Genesis hash mismatch. Host genesis hash: d4e56740…, peer genesis hash: 82270b80…
TRACE 06-29 14:58:52 p2p  net    Disconnecting (our reason: Peer had no use for this node.) from (##2124182c…@54.39.102.75:30005)
TRACE 06-29 14:58:52 p2p  net    Disconnect to (##2124182c…@54.39.102.75:30005)
TRACE 06-29 14:58:52 p2p  net    Closing (Peer had no use for this node.) connection with (##2124182c…@54.39.102.75:30005)
```
	
2. However, Aleth then tries to sync with the node before suddenly closing the peer session:

```
DEBUG 06-29 14:58:52 p2p  sync   Discovered new highest difficulty (44733633866011995653) from peer ##2124182c…
INFO  06-29 14:58:52 p2p  sync   Starting full sync
DEBUG 06-29 14:58:52 p2p  sync   Syncing with peer ##2124182c…
DEBUG 06-29 14:58:52 p2p  peer   Requesting 1 block headers starting from #b41213a3… from ##2124182c… 2124182c…
TRACE 06-29 14:58:52 p2p  net    GetBlockHeaders to (##2124182c…@54.39.102.75:30005)
DEBUG 06-29 14:58:52 p2p  net    Closing peer session with (##2124182c…@54.39.102.75:30005)
```

### PR DESCRIPTION
**Pull request by halfalicious**
Fix #5643 

Fix a bug where Aleth can try to sync with a node after it has failed status validation (e.g. its on a different chain), which results in wasted resources and confusing logs e.g: "starting full sync" being displayed but no blocks being imported.

The root cause is that Aleth can initiate syncing with peers via `Host::forEachPeer` (see `BlockChainSync::continueSync`), and `Host::forEachPeer` iterates through its map of Session weak_ptrs without checking if the session is still connected i.e. the socket isn't closed. This means that the following case can occur:

1. Status packet validation fails (see `BlockChainSync::onPeerStatus`) so Aleth sends a disconnect packet to the remote node (`Host::capabilityHost()::disconnect()`). This results in` Session::disconnect() `being called which results in a write to the socket being queued and the write handler being placed in the boost asio handler queue (see `Session::write`). The socket is then closed. Note that the Session instance is still active until the write is completed and the handler is executed (`Session::shared_from_this()` is captured in the handler).
	
2. Something happens which triggers a call to `BlockChainSync::continueSync` (e.g. a peer session with another node is closed - see `BlockChainSync::onPeerAborting`) - `BlockChainSync::continueSync` makes sync calls for each peer via `host().capabilityHost().forEachPeer()`. Meanwhile the write handler is still sitting in the boost ASIO handler queue so the session is still active. 

3. Eventually the write is performed and the write handler is removed from the queue and executed and the Session instance is destructed. This means that the attempted syncing with the disconnected node is wasted cycles and also makes the logs confusing.

### CODE REVIEW

**Comment by gumb0** [comment]
Is this ready?

**Comment by halfalicious** [comment]
> 
> 
> Is this ready?

@gumb0 Yup! 😄

File: libp2p/Host.cpp [hunk 1]
```diff
@@ -396,6 +396,19 @@ void Host::startPeerSession(Public const& _id, RLP const& _hello,
                   << _s->remoteEndpoint();
 }
 
+/// Get session by id
+shared_ptr<SessionFace> Host::peerSession(NodeID const& _id) const
+{
+    RecursiveGuard l(x_sessions);
+    if (m_sessions.count(_id))
```
Comment (chfast) [inline libp2p/Host.cpp]: Do you search twice, use `.find()`.

File: libp2p/Host.cpp [hunk 2]
```diff
@@ -396,6 +396,19 @@ void Host::startPeerSession(Public const& _id, RLP const& _hello,
...
+    {
+        auto const s = m_sessions[_id].lock();
+        if (s && s->isConnected())
+            return s;
+    }
+    return{};
```
Comment (chfast) [inline libp2p/Host.cpp]: Formatting.

File: libp2p/Host.cpp [hunk 3]
```diff
@@ -1155,13 +1174,16 @@ void Host::forEachPeer(
     RecursiveGuard l(x_sessions);
     vector<shared_ptr<SessionFace>> sessions;
     for (auto const& i : m_sessions)
-        if (shared_ptr<SessionFace> s = i.second.lock())
+    {
+        shared_ptr<SessionFace> s = i.second.lock();
```
Comment (chfast) [inline libp2p/Host.cpp]: Use `auto` as in other cases?

File: libp2p/Host.cpp (hunk 2 above)
Comment (halfalicious) [reply libp2p/Host.cpp]: Thanks, still need to get git clang-format up and running again after a reinstall, will reformat manually for the time-being.

**Comment by halfalicious** [comment]
@gumb0 / @chfast Thanks for the review!
