### PR TITLE
Set new handshake failure reason when disconnect is received instead of hello during RLPX handshake

### LINKED ISSUE #5569: Log disconnect reason when receiving disconnect packet during RLPX handshake
Running a private build of #5568 and I'm seeing some nodes which respond to our auth with an auth-ack then send us a Disconnect message instead of a Hello message. For example:

```
DEBUG 04-14 21:58:07 p2p  rlpx   p2p.connect.egress: HelloPacket to ##15ac307a…@52.176.7.10:30303
DEBUG 04-14 21:58:07 p2p  rlpx   p2p.connect.egress: Frame header from ##15ac307a…@52.176.7.10:30303
DEBUG 04-14 21:58:07 p2p  rlpx   p2p.connect.egress: Successfully decrypted frame header from ##15ac307a…@52.176.7.10:30303. Validating contents...
DEBUG 04-14 21:58:07 p2p  rlpx   p2p.connect.egress: Frame body from ##15ac307a…@52.176.7.10:30303
DEBUG 04-14 21:58:07 p2p  rlpx   p2p.connect.egress: Invalid packet type. Expected: HelloPacket, received: DisconnectPacket (##15ac307a…@52.176.7.10:30303)
DEBUG 04-14 21:58:07 p2p  rlpx   p2p.connect.egress: Handshake Failed (##15ac307a…@52.176.7.10:30303)
```
According to the [Disconnect message description in the RLPX spec](https://github.com/ethereum/devp2p/blob/master/rlpx.md#disconnect-0x01), the message can include an optional reason:
> 
>     reason is an optional integer specifying one of a number of reasons for disconnect:
>         0x00 Disconnect requested;
>         0x01 TCP sub-system error;
>         0x02 Breach of protocol, e.g. a malformed message, bad RLP, incorrect magic number &c.;
>         0x03 Useless peer;
>         0x04 Too many peers;
>         0x05 Already connected;
>         0x06 Incompatible P2P protocol version;
>         0x07 Null node identity received - this is automatically invalid;
>         0x08 Client quitting;
>         0x09 Unexpected identity (i.e. a different identity to a previous connection/what a trusted peer told us).
>         0x0a Identity is the same as this node (i.e. connected to itself);
>         0x0b Timeout on receiving a message (i.e. nothing received since sending last ping);
>         0x10 Some other reason specific to a subprotocol.
> 

We should log this reason (if it's available in the packet).

### PR DESCRIPTION
**Pull request by halfalicious**
We set this new failure reason (`DisconnectRequested`) to avoid garbage collecting these nodes in `Host::run` since this isn't a critical condition - they aren't in violation of the protocol (the p2p capability section of the RLPX handshake spec states that a disconnect can be sent at any time) and we often encounter nodes in practice from whom we receive a disconnect while handshaking but with which we can later successfully complete the handshake and peer with.

Also log the disconnect reason (if present in the received disconnect packet) which fixes #5569

### CODE REVIEW

**Comment by halfalicious** [comment]
Ran some local tests, peer counts are approximately the same:

**Base (without changes)**
- 06-19 08 :  Min:  0 , Max:  6 , Average:  3.54736842105263
- 06-19 09 :  Min:  2 , Max:  6 , Average:  3.84033613445378
- 06-19 10 :  Min:  4 , Max:  7 , Average:  4.63865546218487
- 06-19 11 :  Min:  5 , Max:  7 , Average:  6.46218487394958
- 06-19 12 :  Min:  4 , Max:  7 , Average:  5.27731092436975
- 06-19 13 :  Min:  1 , Max:  6 , Average:  3.99159663865546
- 06-19 14 :  Min:  1 , Max:  3 , Average:  1.95798319327731
- 06-19 15 :  Min:  1 , Max:  3 , Average:  2.59663865546219
- 06-19 16 :  Min:  1 , Max:  3 , Average:  1.48333333333333
- 06-19 17 :  Min:  0 , Max:  4 , Average:  2.13445378151261
- 06-19 18 :  Min:  0 , Max:  5 , Average:  2.69747899159664
- 06-19 19 :  Min:  2 , Max:  4 , Average:  2.71590909090909


**Test (with changes)**
- 06-19 22 :  Min:  0 , Max:  7 , Average:  4.59663865546218
- 06-19 23 :  Min:  5 , Max:  9 , Average:  6.63865546218487
- 06-20 00 :  Min:  6 , Max:  11 , Average:  8.81666666666667
- 06-20 01 :  Min:  7 , Max:  9 , Average:  7.675
- 06-20 02 :  Min:  7 , Max:  9 , Average:  7.70588235294118
- 06-20 03 :  Min:  9 , Max:  10 , Average:  9.1
- 06-20 04 :  Min:  9 , Max:  10 , Average:  9.21008403361344
- 06-20 05 :  Min:  9 , Max:  11 , Average:  9.58333333333333
- 06-20 06 :  Min:  8 , Max:  10 , Average:  9.16806722689076
- 06-20 07 :  Min:  3 , Max:  9 , Average:  6.74789915966387
- 06-20 08 :  Min:  3 , Max:  5 , Average:  3.74166666666667
- 06-20 09 :  Min:  3 , Max:  4 , Average:  3.5
- 06-20 10 :  Min:  2 , Max:  4 , Average:  3.6890756302521
- 06-20 11 :  Min:  1 , Max:  4 , Average:  3.57142857142857
- 06-20 12 :  Min:  1 , Max:  4 , Average:  2.575
- 06-20 13 :  Min:  1 , Max:  3 , Average:  2.75423728813559
- 06-20 14 :  Min:  2 , Max:  3 , Average:  2.625
- 06-20 15 :  Min:  2 , Max:  3 , Average:  2.83333333333333
- 06-20 16 :  Min:  2 , Max:  3 , Average:  2.89915966386555
- 06-20 17 :  Min:  1 , Max:  4 , Average:  3.35833333333333
- 06-20 18 :  Min:  2 , Max:  4 , Average:  3.68333333333333
- 06-20 19 :  Min:  1 , Max:  4 , Average:  2.64615384615385

Also ran some tests on the number of entries in Host::m_peers:

**Base (without changes)**
- 06-17 09 :  Min:  0 , Max:  127 , Average:  89.4878048780488
- 06-17 10 :  Min:  127 , Max:  162 , Average:  158.783333333333
- 06-17 11 :  Min:  161 , Max:  161 , Average:  161
- 06-17 12 :  Min:  161 , Max:  164 , Average:  163.025
- 06-17 13 :  Min:  163 , Max:  164 , Average:  163.352941176471
- 06-17 14 :  Min:  164 , Max:  164 , Average:  164
- 06-17 15 :  Min:  163 , Max:  164 , Average:  163.033613445378
- 06-17 16 :  Min:  163 , Max:  163 , Average:  163
- 06-17 17 :  Min:  162 , Max:  164 , Average:  163.252100840336
- 06-17 18 :  Min:  162 , Max:  164 , Average:  162.908333333333
- 06-17 19 :  Min:  163 , Max:  165 , Average:  164.159663865546
- 06-17 20 :  Min:  165 , Max:  165 , Average:  165

**Test (with changes)**
- 06-19 22 :  Min:  0 , Max:  69 , Average:  57.2773109243698
- 06-19 23 :  Min:  53 , Max:  61 , Average:  56.9579831932773
- 06-20 00 :  Min:  55 , Max:  58 , Average:  57.275
- 06-20 01 :  Min:  49 , Max:  55 , Average:  51.1333333333333
- 06-20 02 :  Min:  49 , Max:  50 , Average:  49.1596638655462
- 06-20 03 :  Min:  48 , Max:  50 , Average:  48.35
- 06-20 04 :  Min:  46 , Max:  48 , Average:  47.0672268907563
- 06-20 05 :  Min:  45 , Max:  47 , Average:  46.0166666666667
- 06-20 06 :  Min:  45 , Max:  46 , Average:  45.7226890756303
- 06-20 07 :  Min:  41 , Max:  47 , Average:  45.4117647058824
- 06-20 08 :  Min:  40 , Max:  42 , Average:  40.5916666666667
- 06-20 09 :  Min:  38 , Max:  40 , Average:  38.8833333333333
- 06-20 10 :  Min:  37 , Max:  39 , Average:  38.3361344537815
- 06-20 11 :  Min:  37 , Max:  38 , Average:  37.9747899159664
- 06-20 12 :  Min:  37 , Max:  38 , Average:  37.225
- 06-20 13 :  Min:  37 , Max:  37 , Average:  37
- 06-20 14 :  Min:  36 , Max:  37 , Average:  36.6416666666667
- 06-20 15 :  Min:  36 , Max:  36 , Average:  36
- 06-20 16 :  Min:  36 , Max:  37 , Average:  36.0084033613445
- 06-20 17 :  Min:  35 , Max:  37 , Average:  35.875
- 06-20 18 :  Min:  36 , Max:  37 , Average:  36.375
- 06-20 19 :  Min:  35 , Max:  36 , Average:  35.2769230769231

File: libp2p/RLPxHandshake.cpp [hunk 1]
```diff
@@ -450,7 +452,35 @@ void RLPXHandshake::transition(boost::system::error_code _ech)
                                         << "Invalid packet type. Expected: "
                                         << p2pPacketTypeToString(HelloPacket)
                                         << ", received: " << p2pPacketTypeToString(packetType);
-                                    m_failureReason = ProtocolError;
+                                    m_failureReason = HandshakeFailureReason::ProtocolError;
+                                    if (packetType == DisconnectPacket)
+                                    {
+                                        try
+                                        {
+                                            // Explicitly avoid RLP::FailIfTooLarge exception if RLP
```
Comment (gumb0) [inline libp2p/RLPxHandshake.cpp]: Avoiding `RLP::FailIfTooLarge` is probably due to requirements of EIP-8

File: CHANGELOG.md [hunk 2]
```diff
@@ -22,6 +22,7 @@
 - Changed: [#5605](https://github.com/ethereum/aleth/pull/5605) Network logging bugfixes and improvements and add warpcap log channel.
 - Changed: [#5628](https://github.com/ethereum/aleth/pull/5628) Don't try to endlessly reconnect to official Ethereum bootnodes.
 - Changed: [#5632](https://github.com/ethereum/aleth/pull/5632) RocksDB support is disabled by default. Enable with `-DROCKSB=ON` CMake option.
+- Changed: [#5635](https://github.com/ethereum/aleth/pull/5635) Enable reconnections to nodes which fail handshake due to common reason.
```
Comment (gumb0) [inline CHANGELOG.md]: As it's a fix of previous PR, I'd skip adding changelog item

File: libp2p/RLPxHandshake.cpp [hunk 3]
```diff
@@ -450,7 +452,35 @@ void RLPXHandshake::transition(boost::system::error_code _ech)
                                         << "Invalid packet type. Expected: "
                                         << p2pPacketTypeToString(HelloPacket)
                                         << ", received: " << p2pPacketTypeToString(packetType);
-                                    m_failureReason = ProtocolError;
+                                    m_failureReason = HandshakeFailureReason::ProtocolError;
+                                    if (packetType == DisconnectPacket)
```
Comment (gumb0) [inline libp2p/RLPxHandshake.cpp]: Better add a comment to explain why we do this (Disconnect is allowed at any moment, so it's not a protocol violation and we should try to reconnect later)

**Comment by gumb0** [comment]
> while it makes sense in principle to garbage collect these peers since they are in breach of the protocol 

I don't think it's a violation, as the spec states:

> At any time, a Disconnect message may be sent.

**Comment by halfalicious** [comment]
> 
> 
> > while it makes sense in principle to garbage collect these peers since they are in breach of the protocol
> 
> I don't think it's a violation, as the spec states:
> 
> > At any time, a Disconnect message may be sent.

Yea, I saw that in the spec, but thought that non-Hello p2pcap messages could only be sent once the session was active:

> 
> The "p2p" capability is present on all connections. After the initial handshake, both sides of the connection must send a Hello message. Upon receiving the Hello message a session is active and any other message may be sent. Implementations must ignore any difference in protocol version for forward-compatibility reasons. When communicating with a peer of lower version, implementations should try to mimic that version.
> 
> At any time, a Disconnect message may be sent.

However, after re-reading this and given the current behavior it looks like the last sentence means that disconnect messages can be sent at any point during the handshake (well, after the key material has been exchanged so that they can be decrypted)
