### PR TITLE
Fix segmentation fault during syncing

### LINKED ISSUE #5832: Aleth 1.7.0 crash on Ubuntu 18.04 LTS
First Time :
```
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `./online_wallet -d cpp_ethereum_data/ --db-path cpp_ethereum_data/ --http-rpc-p'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x000055d52e82c49f in dev::eth::EthereumPeer::requestBlockHeaders (this=this@entry=0x7f3f201bae50, _startHash=..., _count=_count@entry=1, _skip=_skip@entry=0, _reverse=_reverse@entry=false)
    at /home/teddy/project/cpp-ethereum/libethereum/EthereumPeer.cpp:112
112	/home/teddy/project/cpp-ethereum/libethereum/EthereumPeer.cpp: No such file or directory.
[Current thread is 1 (Thread 0x7f3f90435700 (LWP 11168))]
(gdb) bt
#0  0x000055d52e82c49f in dev::eth::EthereumPeer::requestBlockHeaders (this=this@entry=0x7f3f201bae50, _startHash=..., _count=_count@entry=1, _skip=_skip@entry=0, _reverse=_reverse@entry=false)
    at /home/teddy/project/cpp-ethereum/libethereum/EthereumPeer.cpp:112
#1  0x000055d52e89b32b in dev::eth::BlockChainSync::syncPeer (this=this@entry=0x55d530fff490, _peerID=..., _force=_force@entry=true) at /home/teddy/project/cpp-ethereum/libethereum/BlockChainSync.cpp:269
#2  0x000055d52e89e84b in dev::eth::BlockChainSync::onPeerNewHashes (this=0x55d530fff490, _peerID=..., _hashes=...) at /home/teddy/project/cpp-ethereum/libethereum/BlockChainSync.cpp:934
#3  0x000055d52e81baf6 in (anonymous namespace)::EthereumPeerObserver::onPeerNewHashes (this=0x55d530c15590, _peerID=..., _hashes=...) at /home/teddy/project/cpp-ethereum/libethereum/EthereumCapability.cpp:133
#4  0x000055d52e81fa2a in dev::eth::EthereumCapability::interpretCapabilityPacket (this=this@entry=0x55d5305f7d40, _peerID=..., _id=_id@entry=1, _r=...) at /home/teddy/project/cpp-ethereum/libethereum/EthereumCapability.cpp:767
#5  0x000055d52eb04799 in dev::p2p::Session::readPacket (this=0x7f3f2d1b5f70, _capId=<optimized out>, _packetType=_packetType@entry=17, _r=...) at /home/teddy/project/cpp-ethereum/libp2p/Session.cpp:120
#6  0x000055d52eb04e14 in dev::p2p::Session::<lambda(boost::system::error_code, std::size_t)>::<lambda(boost::system::error_code, std::size_t)>::operator()(boost::system::error_code, std::size_t) const (
    __closure=__closure@entry=0x7f3f904349a8, ec=..., length=<optimized out>) at /home/teddy/project/cpp-ethereum/libp2p/Session.cpp:384
#7  0x000055d52eb05287 in boost::asio::detail::read_op<boost::asio::basic_stream_socket<boost::asio::ip::tcp, boost::asio::executor>, boost::asio::mutable_buffers_1, const boost::asio::mutable_buffer*, boost::asio::detail::transfer_all_t, dev::p2p::Session::doRead()::<lambda(boost::system::error_code, std::size_t)>::<lambda(boost::system::error_code, std::size_t)> >::operator()(const boost::system::error_code &, std::size_t, int) (this=0x7f3f90434980, ec=..., 
    bytes_transferred=<optimized out>, start=start@entry=0) at /home/teddy/.hunter/_Base/c022f0c/af6c4e5/6d1bd54/Install/include/boost/asio/impl/read.hpp:373
#8  0x000055d52eb0674d in boost::asio::detail::binder2<boost::asio::detail::read_op<boost::asio::basic_stream_socket<boost::asio::ip::tcp, boost::asio::executor>, boost::asio::mutable_buffers_1, const boost::asio::mutable_buffer*, boost::asio::detail::transfer_all_t, dev::p2p::Session::doRead()::<lambda(boost::system::error_code, std::size_t)>::<lambda(boost::system::error_code, std::size_t)> >, boost::system::error_code, long unsigned int>::operator() (this=0x7f3f90434980)
    at /home/teddy/.hunter/_Base/c022f0c/af6c4e5/6d1bd54/Install/include/boost/asio/detail/bind_handler.hpp:164
#9  boost::asio::asio_handler_invoke<boost::asio::detail::binder2<boost::asio::detail::read_op<boost::asio::basic_stream_socket<boost::asio::ip::tcp>, boost::asio::mutable_buffers_1, const boost::asio::mutable_buffer*, boost::asio::detail::transfer_all_t, dev::p2p::Session::doRead()::<lambda(boost::system::error_code, std::size_t)>::<lambda(boost::system::error_code, std::size_t)> >, boost::system::error_code, long unsigned int> > (function=...)
    at /home/teddy/.hunter/_Base/c022f0c/af6c4e5/6d1bd54/Install/include/boost/asio/handler_invoke_hook.hpp:69
#10 boost_asio_handler_invoke_helpers::invoke<boost::asio::detail::binder2<boost::asio::detail::read_op<boost::asio::basic_stream_socket<boost::asio::ip::tcp>, boost::asio::mutable_buffers_1, const boost::asio::mutable_buffer*, boost::asio::detail::transfer_all_t, dev::p2p::Session::doRead()::<lambda(boost::system::error_code, std::size_t)>::<lambda(boost::system::error_code, std::size_t)> >, boost::system::error_code, long unsigned int>, dev::p2p::Session::doRead()::<lambda(boost::system::error_code, std::size_t)>::<lambda(boost::system::error_code, std::size_t)> > (context=..., function=...) at /home/teddy/.hunter/_Base/c022f0c/af6c4e5/6d1bd54/Install/include/boost/asio/detail/handler_invoke_helpers.hpp:37
#11 boost::asio::detail::asio_handler_invoke<boost::asio::detail::binder2<boost::asio::detail::read_op<boost::asio::basic_stream_socket<boost::asio::ip::tcp>, boost::asio::mutable_buffers_1, const boost::asio::mutable_buffer*, boost::asio::detail::transfer_all_t, dev::p2p::Session::doRead()::<lambda(boost::system::error_code, std::size_t)>::<lambda(boost::system::error_code, std::size_t)> >, boost::system::error_code, long unsigned int>, boost::asio::basic_stream_socket<boost::asio::ip::tcp>, boost::asio::mutable_buffers_1, const boost::asio::mutable_buffer*, boost::asio::detail::transfer_all_t, dev::p2p::Session::doRead()::<lambda(boost::system::error_code, std::size_t)>::<lambda(boost::system::error_code, std::size_t)> > (this_handler=<optimized out>, function=...) at /home/teddy/.hunter/_Base/c022f0c/af6c4e5/6d1bd54/Install/include/boost/asio/impl/read.hpp:428
#12 boost_asio_handler_invoke_helpers::invoke<boost::asio::detail::binder2<boost::asio::detail::read_op<boost::asio::basic_stream_socket<boost::asio::ip::tcp>, boost::asio::mutable_buffers_1, const boost::asio::mutable_buffer*, boost::asio::detail::transfer_all_t, dev::p2p::Session::doRead()::<lambda(boost::system::error_code, std::size_t)>::<lambda(boost::system::error_code, std::size_t)> >, boost::system::error_code, long unsigned int>, boost::asio::detail::read_op<boost::asio::basic_stream_socket<boost::asio::ip::tcp>, boost::asio::mutable_buffers_1, const boost::asio::mutable_buffer*, boost::asio::detail::transfer_all_t, dev::p2p::Session::doRead()::<lambda(boost::system::error_code, std::size_t)>::<lambda(boost::system::error_code, std::size_t)> > > (context=..., function=...) at /home/teddy/.hunter/_Base/c022f0c/af6c4e5/6d1bd54/Install/include/boost/asio/detail/handler_invoke_helpers.hpp:37
#13 boost::asio::detail::asio_handler_invoke<boost::asio::detail::binder2<boost::asio::detail::read_op<boost::asio::basic_stream_socket<boost::asio::ip::tcp>, boost::asio::mutable_buffers_1, const boost::asio::mutable_buffer*, boost::asio::detail::transfer_all_t, dev::p2p::Session::doRead()::<lambda(boost::system::error_code, std::size_t)>::<lambda(boost::system::error_code, std::size_t)> >, boost::system::error_code, long unsigned int>, boost::asio::detail::read_op<boost::asio::basic_stream_socket<boost::asio::ip::tcp>, boost::asio::mutable_buffers_1, const boost::asio::mutable_buffer*, boost::asio::detail::transfer_all_t, dev::p2p::Session::doRead()::<lambda(boost::system::error_code, std::size_t)>::<lambda(boost::system::error_code, std::size_t)> >, boost::system::error_code, long unsigned int> (this_handler=<optimized out>, function=...) at /home/teddy/.hunter/_Base/c022f0c/af6c4e5/6d1bd54/Install/include/boost/asio/detail/bind_handler.hpp:207
#14 boost_asio_handler_invoke_helpers::invoke<boost::asio::detail::binder2<boost::asio::detail::read_op<boost::asio::basic_stream_socket<boost::asio::ip::tcp>, boost::asio::mutable_buffers_1, const boost::asio::mutable_buffer*, boost::asio::detail::transfer_all_t, dev::p2p::Session::doRead()::<lambda(boost::system::error_code, std::size_t)>::<lambda(boost::system::error_code, std::size_t)> >, boost::system::error_code, long unsigned int>, boost::asio::detail::binder2<boost::asio::detail::read_op<boost::asio::basic_stream_socket<boost::asio::ip::tcp>, boost::asio::mutable_buffers_1, const boost::asio::mutable_buffer*, boost::asio::detail::transfer_all_t, dev::p2p::Session::doRead()::<lambda(boost::system::error_code, std::size_t)>::<lambda(boost::system::error_code, std::size_t)> >, boost::system::error_code, long unsigned int> > (context=..., function=...)
    at /home/teddy/.hunter/_Base/c022f0c/af6c4e5/6d1bd54/Install/include/boost/asio/detail/handler_invoke_helpers.hpp:37
#15 boost::asio::detail::io_object_executor<boost::asio::executor>::dispatch<boost::asio::detail::binder2<boost::asio::detail::read_op<boost::asio::basic_stream_socket<boost::asio::ip::tcp>, boost::asio::mutable_buffers_1, const boost::asio::mutable_buffer*, boost::asio::detail::transfer_all_t, dev::p2p::Session::doRead()::<lambda(boost::system::error_code, std::size_t)>::<lambda(boost::system::error_code, std::size_t)> >, boost::system::error_code, long unsigned int>, std::allocator<void> > (a=..., f=..., this=<synthetic pointer>) at /home/teddy/.hunter/_Base/c022f0c/af6c4e5/6d1bd54/Install/include/boost/asio/detail/io_object_executor.hpp:117
#16 boost::asio::detail::handler_work<boost::asio::detail::read_op<boost::asio::basic_stream_socket<boost::asio::ip::tcp, boost::asio::executor>, boost::asio::mutable_buffers_1, const boost::asio::mutable_buffer*, boost::asio::detail::transfer_all_t, dev::p2p::Session::doRead()::<lambda(boost::system::error_code, std::size_t)>::<lambda(boost::system::error_code, std::size_t)> >, boost::asio::detail::io_object_executor<boost::asio::executor>, boost::asio::detail::io_object_executor<boost::asio::executor> >::complete<boost::asio::detail::binder2<boost::asio::detail::read_op<boost::asio::basic_stream_socket<boost::asio::ip::tcp>, boost::asio::mutable_buffers_1, const boost::asio::mutable_buffer*, boost::asio::detail::transfer_all_t, dev::p2p::Session::doRead()::<lambda(boost::system::error_code, std::size_t)>::<lambda(boost::system::error_code, std::size_t)> >, boost::system::error_code, long unsigned int> > (handler=..., function=..., 
    this=<synthetic pointer>) at /home/teddy/.hunter/_Base/c022f0c/af6c4e5/6d1bd54/Install/include/boost/asio/detail/handler_work.hpp:72
#17 boost::asio::detail::reactive_socket_recv_op<boost::asio::mutable_buffers_1, boost::asio::detail::read_op<boost::asio::basic_stream_socket<boost::asio::ip::tcp, boost::asio::executor>, boost::asio::mutable_buffers_1, const boost::asio::mutable_buffer*, boost::asio::detail::transfer_all_t, dev::p2p::Session::doRead()::<lambda(boost::system::error_code, std::size_t)>::<lambda(boost::system::error_code, std::size_t)> >, boost::asio::detail::io_object_executor<boost::asio::executor> >::do_complete(void *, boost::asio::detail::operation *, const boost::system::error_code &, std::size_t) (owner=0x55d530c59600, base=<optimized out>)
    at /home/teddy/.hunter/_Base/c022f0c/af6c4e5/6d1bd54/Install/include/boost/asio/detail/reactive_socket_recv_op.hpp:123
#18 0x000055d52eacbaff in boost::asio::detail::scheduler_operation::complete (bytes_transferred=<optimized out>, ec=..., owner=0x55d530c59600, this=<optimized out>)
    at /home/teddy/.hunter/_Base/c022f0c/af6c4e5/6d1bd54/Install/include/boost/asio/detail/scheduler_operation.hpp:40
#19 boost::asio::detail::scheduler::do_run_one (ec=..., this_thread=..., lock=..., this=0x55d530c59600) at /home/teddy/.hunter/_Base/c022f0c/af6c4e5/6d1bd54/Install/include/boost/asio/detail/impl/scheduler.ipp:447
#20 boost::asio::detail::scheduler::run (this=0x55d530c59600, ec=...) at /home/teddy/.hunter/_Base/c022f0c/af6c4e5/6d1bd54/Install/include/boost/asio/detail/impl/scheduler.ipp:200
#21 0x000055d52eab571d in boost::asio::io_context::run (this=0x7fffabf7fe38) at /home/teddy/.hunter/_Base/c022f0c/af6c4e5/6d1bd54/Install/include/boost/asio/impl/io_context.ipp:63
---Type <return> to continue, or q <return> to quit---
#22 dev::p2p::Host::doWork (this=0x7fffabf7fce0) at /home/teddy/project/cpp-ethereum/libp2p/Host.cpp:918
#23 0x000055d52e9406b2 in dev::Worker::workLoop (this=0x7fffabf7fce0) at /home/teddy/project/cpp-ethereum/libdevcore/Worker.cpp:124
#24 0x000055d52e940fd4 in dev::Worker::<lambda()>::operator() (__closure=0x55d53050abd8) at /home/teddy/project/cpp-ethereum/libdevcore/Worker.cpp:46
#25 std::__invoke_impl<void, dev::Worker::startWorking()::<lambda()> > (__f=...) at /usr/include/c++/7/bits/invoke.h:60
#26 std::__invoke<dev::Worker::startWorking()::<lambda()> > (__fn=...) at /usr/include/c++/7/bits/invoke.h:95
#27 std::thread::_Invoker<std::tuple<dev::Worker::startWorking()::<lambda()> > >::_M_invoke<0> (this=0x55d53050abd8) at /usr/include/c++/7/thread:234
#28 std::thread::_Invoker<std::tuple<dev::Worker::startWorking()::<lambda()> > >::operator() (this=0x55d53050abd8) at /usr/include/c++/7/thread:243
#29 std::thread::_State_impl<std::thread::_Invoker<std::tuple<dev::Worker::startWorking()::<lambda()> > > >::_M_run(void) (this=0x55d53050abd0) at /usr/include/c++/7/thread:186
#30 0x00007f3fb2c1957f in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#31 0x00007f3fb2eec6db in start_thread (arg=0x7f3f90435700) at pthread_create.c:463
#32 0x00007f3fb22d688f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

Second Time:
```
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `./online_wallet -d cpp_ethereum_data/ --db-path cpp_ethereum_data/ --http-rpc-p'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x000055a6a94dc49f in dev::eth::EthereumPeer::requestBlockHeaders (this=this@entry=0x7f2838a9a050, _startHash=..., _count=_count@entry=1, _skip=_skip@entry=0, _reverse=_reverse@entry=false)
    at /home/teddy/project/cpp-ethereum/libethereum/EthereumPeer.cpp:112
112	/home/teddy/project/cpp-ethereum/libethereum/EthereumPeer.cpp: No such file or directory.
[Current thread is 1 (Thread 0x7f28a09fb700 (LWP 8070))]
(gdb) bt
#0  0x000055a6a94dc49f in dev::eth::EthereumPeer::requestBlockHeaders (this=this@entry=0x7f2838a9a050, _startHash=..., _count=_count@entry=1, _skip=_skip@entry=0, _reverse=_reverse@entry=false)
    at /home/teddy/project/cpp-ethereum/libethereum/EthereumPeer.cpp:112
#1  0x000055a6a954b32b in dev::eth::BlockChainSync::syncPeer (this=this@entry=0x55a7707d6130, _peerID=..., _force=_force@entry=true) at /home/teddy/project/cpp-ethereum/libethereum/BlockChainSync.cpp:269
#2  0x000055a6a954e84b in dev::eth::BlockChainSync::onPeerNewHashes (this=0x55a7707d6130, _peerID=..., _hashes=...) at /home/teddy/project/cpp-ethereum/libethereum/BlockChainSync.cpp:934
#3  0x000055a6a94cbaf6 in (anonymous namespace)::EthereumPeerObserver::onPeerNewHashes (this=0x55a7712650f0, _peerID=..., _hashes=...) at /home/teddy/project/cpp-ethereum/libethereum/EthereumCapability.cpp:133
#4  0x000055a6a94cfa2a in dev::eth::EthereumCapability::interpretCapabilityPacket (this=this@entry=0x55a742425880, _peerID=..., _id=_id@entry=1, _r=...) at /home/teddy/project/cpp-ethereum/libethereum/EthereumCapability.cpp:767
#5  0x000055a6a97b4799 in dev::p2p::Session::readPacket (this=0x7f289d186c50, _capId=<optimized out>, _packetType=_packetType@entry=17, _r=...) at /home/teddy/project/cpp-ethereum/libp2p/Session.cpp:120
#6  0x000055a6a97b4e14 in dev::p2p::Session::<lambda(boost::system::error_code, std::size_t)>::<lambda(boost::system::error_code, std::size_t)>::operator()(boost::system::error_code, std::size_t) const (
    __closure=__closure@entry=0x7f28a09fa9a8, ec=..., length=<optimized out>) at /home/teddy/project/cpp-ethereum/libp2p/Session.cpp:384
#7  0x000055a6a97b5287 in boost::asio::detail::read_op<boost::asio::basic_stream_socket<boost::asio::ip::tcp, boost::asio::executor>, boost::asio::mutable_buffers_1, const boost::asio::mutable_buffer*, boost::asio::detail::transfer_all_t, dev::p2p::Session::doRead()::<lambda(boost::system::error_code, std::size_t)>::<lambda(boost::system::error_code, std::size_t)> >::operator()(const boost::system::error_code &, std::size_t, int) (this=0x7f28a09fa980, ec=..., 
    bytes_transferred=<optimized out>, start=start@entry=0) at /home/teddy/.hunter/_Base/c022f0c/af6c4e5/6d1bd54/Install/include/boost/asio/impl/read.hpp:373
#8  0x000055a6a97b674d in boost::asio::detail::binder2<boost::asio::detail::read_op<boost::asio::basic_stream_socket<boost::asio::ip::tcp, boost::asio::executor>, boost::asio::mutable_buffers_1, const boost::asio::mutable_buffer*, boost::asio::detail::transfer_all_t, dev::p2p::Session::doRead()::<lambda(boost::system::error_code, std::size_t)>::<lambda(boost::system::error_code, std::size_t)> >, boost::system::error_code, long unsigned int>::operator() (this=0x7f28a09fa980)
    at /home/teddy/.hunter/_Base/c022f0c/af6c4e5/6d1bd54/Install/include/boost/asio/detail/bind_handler.hpp:164
#9  boost::asio::asio_handler_invoke<boost::asio::detail::binder2<boost::asio::detail::read_op<boost::asio::basic_stream_socket<boost::asio::ip::tcp>, boost::asio::mutable_buffers_1, const boost::asio::mutable_buffer*, boost::asio::detail::transfer_all_t, dev::p2p::Session::doRead()::<lambda(boost::system::error_code, std::size_t)>::<lambda(boost::system::error_code, std::size_t)> >, boost::system::error_code, long unsigned int> > (function=...)
    at /home/teddy/.hunter/_Base/c022f0c/af6c4e5/6d1bd54/Install/include/boost/asio/handler_invoke_hook.hpp:69
#10 boost_asio_handler_invoke_helpers::invoke<boost::asio::detail::binder2<boost::asio::detail::read_op<boost::asio::basic_stream_socket<boost::asio::ip::tcp>, boost::asio::mutable_buffers_1, const boost::asio::mutable_buffer*, boost::asio::detail::transfer_all_t, dev::p2p::Session::doRead()::<lambda(boost::system::error_code, std::size_t)>::<lambda(boost::system::error_code, std::size_t)> >, boost::system::error_code, long unsigned int>, dev::p2p::Session::doRead()::<lambda(boost::system::error_code, std::size_t)>::<lambda(boost::system::error_code, std::size_t)> > (context=..., function=...) at /home/teddy/.hunter/_Base/c022f0c/af6c4e5/6d1bd54/Install/include/boost/asio/detail/handler_invoke_helpers.hpp:37
#11 boost::asio::detail::asio_handler_invoke<boost::asio::detail::binder2<boost::asio::detail::read_op<boost::asio::basic_stream_socket<boost::asio::ip::tcp>, boost::asio::mutable_buffers_1, const boost::asio::mutable_buffer*, boost::asio::detail::transfer_all_t, dev::p2p::Session::doRead()::<lambda(boost::system::error_code, std::size_t)>::<lambda(boost::system::error_code, std::size_t)> >, boost::system::error_code, long unsigned int>, boost::asio::basic_stream_socket<boost::asio::ip::tcp>, boost::asio::mutable_buffers_1, const boost::asio::mutable_buffer*, boost::asio::detail::transfer_all_t, dev::p2p::Session::doRead()::<lambda(boost::system::error_code, std::size_t)>::<lambda(boost::system::error_code, std::size_t)> > (this_handler=<optimized out>, function=...) at /home/teddy/.hunter/_Base/c022f0c/af6c4e5/6d1bd54/Install/include/boost/asio/impl/read.hpp:428
#12 boost_asio_handler_invoke_helpers::invoke<boost::asio::detail::binder2<boost::asio::detail::read_op<boost::asio::basic_stream_socket<boost::asio::ip::tcp>, boost::asio::mutable_buffers_1, const boost::asio::mutable_buffer*, boost::asio::detail::transfer_all_t, dev::p2p::Session::doRead()::<lambda(boost::system::error_code, std::size_t)>::<lambda(boost::system::error_code, std::size_t)> >, boost::system::error_code, long unsigned int>, boost::asio::detail::read_op<boost::asio::basic_stream_socket<boost::asio::ip::tcp>, boost::asio::mutable_buffers_1, const boost::asio::mutable_buffer*, boost::asio::detail::transfer_all_t, dev::p2p::Session::doRead()::<lambda(boost::system::error_code, std::size_t)>::<lambda(boost::system::error_code, std::size_t)> > > (context=..., function=...) at /home/teddy/.hunter/_Base/c022f0c/af6c4e5/6d1bd54/Install/include/boost/asio/detail/handler_invoke_helpers.hpp:37
#13 boost::asio::detail::asio_handler_invoke<boost::asio::detail::binder2<boost::asio::detail::read_op<boost::asio::basic_stream_socket<boost::asio::ip::tcp>, boost::asio::mutable_buffers_1, const boost::asio::mutable_buffer*, boost::asio::detail::transfer_all_t, dev::p2p::Session::doRead()::<lambda(boost::system::error_code, std::size_t)>::<lambda(boost::system::error_code, std::size_t)> >, boost::system::error_code, long unsigned int>, boost::asio::detail::read_op<boost::asio::basic_stream_socket<boost::asio::ip::tcp>, boost::asio::mutable_buffers_1, const boost::asio::mutable_buffer*, boost::asio::detail::transfer_all_t, dev::p2p::Session::doRead()::<lambda(boost::system::error_code, std::size_t)>::<lambda(boost::system::error_code, std::size_t)> >, boost::system::error_code, long unsigned int> (this_handler=<optimized out>, function=...) at /home/teddy/.hunter/_Base/c022f0c/af6c4e5/6d1bd54/Install/include/boost/asio/detail/bind_handler.hpp:207
#14 boost_asio_handler_invoke_helpers::invoke<boost::asio::detail::binder2<boost::asio::detail::read_op<boost::asio::basic_stream_socket<boost::asio::ip::tcp>, boost::asio::mutable_buffers_1, const boost::asio::mutable_buffer*, boost::asio::detail::transfer_all_t, dev::p2p::Session::doRead()::<lambda(boost::system::error_code, std::size_t)>::<lambda(boost::system::error_code, std::size_t)> >, boost::system::error_code, long unsigned int>, boost::asio::detail::binder2<boost::asio::detail::read_op<boost::asio::basic_stream_socket<boost::asio::ip::tcp>, boost::asio::mutable_buffers_1, const boost::asio::mutable_buffer*, boost::asio::detail::transfer_all_t, dev::p2p::Session::doRead()::<lambda(boost::system::error_code, std::size_t)>::<lambda(boost::system::error_code, std::size_t)> >, boost::system::error_code, long unsigned int> > (context=..., function=...)
    at /home/teddy/.hunter/_Base/c022f0c/af6c4e5/6d1bd54/Install/include/boost/asio/detail/handler_invoke_helpers.hpp:37
#15 boost::asio::detail::io_object_executor<boost::asio::executor>::dispatch<boost::asio::detail::binder2<boost::asio::detail::read_op<boost::asio::basic_stream_socket<boost::asio::ip::tcp>, boost::asio::mutable_buffers_1, const boost::asio::mutable_buffer*, boost::asio::detail::transfer_all_t, dev::p2p::Session::doRead()::<lambda(boost::system::error_code, std::size_t)>::<lambda(boost::system::error_code, std::size_t)> >, boost::system::error_code, long unsigned int>, std::allocator<void> > (a=..., f=..., this=<synthetic pointer>) at /home/teddy/.hunter/_Base/c022f0c/af6c4e5/6d1bd54/Install/include/boost/asio/detail/io_object_executor.hpp:117
#16 boost::asio::detail::handler_work<boost::asio::detail::read_op<boost::asio::basic_stream_socket<boost::asio::ip::tcp, boost::asio::executor>, boost::asio::mutable_buffers_1, const boost::asio::mutable_buffer*, boost::asio::detail::transfer_all_t, dev::p2p::Session::doRead()::<lambda(boost::system::error_code, std::size_t)>::<lambda(boost::system::error_code, std::size_t)> >, boost::asio::detail::io_object_executor<boost::asio::executor>, boost::asio::detail::io_object_executor<boost::asio::executor> >::complete<boost::asio::detail::binder2<boost::asio::detail::read_op<boost::asio::basic_stream_socket<boost::asio::ip::tcp>, boost::asio::mutable_buffers_1, const boost::asio::mutable_buffer*, boost::asio::detail::transfer_all_t, dev::p2p::Session::doRead()::<lambda(boost::system::error_code, std::size_t)>::<lambda(boost::system::error_code, std::size_t)> >, boost::system::error_code, long unsigned int> > (handler=..., function=..., 
    this=<synthetic pointer>) at /home/teddy/.hunter/_Base/c022f0c/af6c4e5/6d1bd54/Install/include/boost/asio/detail/handler_work.hpp:72
#17 boost::asio::detail::reactive_socket_recv_op<boost::asio::mutable_buffers_1, boost::asio::detail::read_op<boost::asio::basic_stream_socket<boost::asio::ip::tcp, boost::asio::executor>, boost::asio::mutable_buffers_1, const boost::asio::mutable_buffer*, boost::asio::detail::transfer_all_t, dev::p2p::Session::doRead()::<lambda(boost::system::error_code, std::size_t)>::<lambda(boost::system::error_code, std::size_t)> >, boost::asio::detail::io_object_executor<boost::asio::executor> >::do_complete(void *, boost::asio::detail::operation *, const boost::system::error_code &, std::size_t) (owner=0x55a6abe83600, base=<optimized out>)
    at /home/teddy/.hunter/_Base/c022f0c/af6c4e5/6d1bd54/Install/include/boost/asio/detail/reactive_socket_recv_op.hpp:123
#18 0x000055a6a977baff in boost::asio::detail::scheduler_operation::complete (bytes_transferred=<optimized out>, ec=..., owner=0x55a6abe83600, this=<optimized out>)
    at /home/teddy/.hunter/_Base/c022f0c/af6c4e5/6d1bd54/Install/include/boost/asio/detail/scheduler_operation.hpp:40
#19 boost::asio::detail::scheduler::do_run_one (ec=..., this_thread=..., lock=..., this=0x55a6abe83600) at /home/teddy/.hunter/_Base/c022f0c/af6c4e5/6d1bd54/Install/include/boost/asio/detail/impl/scheduler.ipp:447
#20 boost::asio::detail::scheduler::run (this=0x55a6abe83600, ec=...) at /home/teddy/.hunter/_Base/c022f0c/af6c4e5/6d1bd54/Install/include/boost/asio/detail/impl/scheduler.ipp:200
#21 0x000055a6a976571d in boost::asio::io_context::run (this=0x7ffc7c238fc8) at /home/teddy/.hunter/_Base/c022f0c/af6c4e5/6d1bd54/Install/include/boost/asio/impl/io_context.ipp:63
---Type <return> to continue, or q <return> to quit---
#22 dev::p2p::Host::doWork (this=0x7ffc7c238e70) at /home/teddy/project/cpp-ethereum/libp2p/Host.cpp:918
#23 0x000055a6a95f06b2 in dev::Worker::workLoop (this=0x7ffc7c238e70) at /home/teddy/project/cpp-ethereum/libdevcore/Worker.cpp:124
#24 0x000055a6a95f0fd4 in dev::Worker::<lambda()>::operator() (__closure=0x55a76fdfa4d8) at /home/teddy/project/cpp-ethereum/libdevcore/Worker.cpp:46
#25 std::__invoke_impl<void, dev::Worker::startWorking()::<lambda()> > (__f=...) at /usr/include/c++/7/bits/invoke.h:60
#26 std::__invoke<dev::Worker::startWorking()::<lambda()> > (__fn=...) at /usr/include/c++/7/bits/invoke.h:95
#27 std::thread::_Invoker<std::tuple<dev::Worker::startWorking()::<lambda()> > >::_M_invoke<0> (this=0x55a76fdfa4d8) at /usr/include/c++/7/thread:234
#28 std::thread::_Invoker<std::tuple<dev::Worker::startWorking()::<lambda()> > >::operator() (this=0x55a76fdfa4d8) at /usr/include/c++/7/thread:243
#29 std::thread::_State_impl<std::thread::_Invoker<std::tuple<dev::Worker::startWorking()::<lambda()> > > >::_M_run(void) (this=0x55a76fdfa4d0) at /usr/include/c++/7/thread:186
#30 0x00007f28c50b257f in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#31 0x00007f28c53856db in start_thread (arg=0x7f28a09fb700) at pthread_create.c:463
#32 0x00007f28c476f88f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

### PR DESCRIPTION
**Pull request by halfalicious**
Fix #5832, #5633 

I suspect the segmentation fault is occurring when a peer reconnects while its disconnect is
still pending (see [here ](https://github.com/ethereum/aleth/issues/5633#issuecomment-550934074)for a detailed description), which results in a live `Session ` but no entry in
`EthereumCapability::m_peers`.

`EthereumCapability::interpretCapabilityPacket` directly accesses `m_peers` via the `[] `operator rather than using a lookup function, which can cause a segfault if the entry with the node ID has already been removed.

This fix will trigger an exception to be thrown when the peer being looked up is not present in `EthereumCapability::m_peers`. This isn't ideal, but is good enough for now until we can design a proper fix for the "reconnect during pending disconnect" issue (#5835)

### CODE REVIEW

**Comment by gumb0** [comment]
Do I understand correctly that the reason for crash is that new `EthereumPeer` is default-constructed by `operator []` and then it tries to acccess null `EthereumPeer::m_host` pointer and crashes?

Then could we remove default constructor of `EthereumPeer` ?

File: libethereum/EthereumCapability.cpp [hunk 1]
```diff
@@ -629,7 +629,7 @@ void EthereumCapability::onDisconnect(NodeID const& _peerID)
 bool EthereumCapability::interpretCapabilityPacket(
     NodeID const& _peerID, unsigned _id, RLP const& _r)
 {
-    auto& peer = m_peers[_peerID];
+    auto& peer = this->peer(_peerID);
```
Comment (gumb0) [inline libethereum/EthereumCapability.cpp]:
```suggestion
    auto& peer = peer(_peerID);
```

Comment (halfalicious) [reply libethereum/EthereumCapability.cpp]: I intentionally went with `this->peer ` since otherwise I get a compiler error:
```
C:\Users\nilse\Documents\Code\aleth\libethereum\EthereumCapability.cpp(632,22): error C3536:  'peer': cannot be used before it is initialized [C:\Users\nilse\Documents\Code\aleth\build\libethereum\ethereum.vcxproj]
C:\Users\nilse\Documents\Code\aleth\libethereum\EthereumCapability.cpp(632,18): error C2064:  term does not evaluate to a function taking 1 arguments [C:\Users\nilse\Documents\Code\aleth\build\libethereum\ethereum.vcxproj]
C:\Users\nilse\Documents\Code\aleth\libethereum\EthereumCapability.cpp(654,46): error C2664:  'void dev::eth::EthereumPeerObserverFace::onPeerStatus(const dev::eth::EthereumPeer &)': cannot convert argument 1 from 'int' to 'const dev::e
th::EthereumPeer &' [C:\Users\nilse\Documents\Code\aleth\build\libethereum\ethereum.vcxproj]
```

**Comment by halfalicious** [comment]
Ran a sync overnight on Linux for ~9 hours and didn't hit the AV

File: libethereum/EthereumCapability.cpp (hunk 1 above)
Comment (gumb0) [reply libethereum/EthereumCapability.cpp]: Rename `peer` variable then

File: CHANGELOG.md [hunk 2]
```diff
@@ -3,6 +3,7 @@
 ## [1.7.1] - 2019-11-18
 
 - Fixed: [#5830](https://github.com/ethereum/aleth/pull/5830) Fix cost of ECADD and ECMULL for Istanbul in Mainnet and Ropsten chain configs.
+- Fixed: [#5834](https://github.com/ethereum/aleth/pull/5834) Fix segmentation fault during sync.
```
Comment (gumb0) [inline CHANGELOG.md]: Let's merge to master first, rebase this and move to 1.8.0 section

**Comment by halfalicious** [comment]
> 
> 
> Do I understand correctly that the reason for crash is that new `EthereumPeer` is default-constructed by `operator []` and then it tries to acccess null `EthereumPeer::m_host` pointer and crashes?
> 
> Then could we remove default constructor of `EthereumPeer` ?

@gumb0: Yes, that's correct - attempting to retrieve an element from the unordered map which doesn't exist (via the [] operator) results in it being default constructed and inserted, then returned. When we try to deref m_host we get the av.

Good idea about removing the default ctor, I'll do that.

**Comment by halfalicious** [comment]
Rebased and updated changelog
