### PR TITLE
testeth fix error output for non consensus tests

### LINKED ISSUE #5584: Consensus tests related error messages when running unit tests
Now I see error messages from https://github.com/ethereum/aleth/pull/5558 when running unit tests
```
> test/testeth -t network/net/udpOnce
Running tests using path: "../../test/jsontests"
Running 1 test case...
Test Case "udpOnce": 

*** No errors detected
ERROR: Expected a single test to be passed: net/udpOnce
```

Please fix this.

### PR DESCRIPTION
**Pull request by winsvega**
fixes #5584

### CODE REVIEW

File: test/tools/libtesteth/TestOutputHelper.cpp [hunk 1]
```diff
@@ -135,11 +135,13 @@ void TestOutputHelper::checkUnfinishedTestFolders()
 
     if (!filter.empty())
     {
-        if (m_finishedTestFoldersMap.size() != 1)
+        if (m_finishedTestFoldersMap.size() > 1)
         {
             std::cerr << "ERROR: Expected a single test to be passed: " << filter << "\n";
             return;
         }
+        if (m_finishedTestFoldersMap.size() == 0)
```
Comment (gumb0) [inline test/tools/libtesteth/TestOutputHelper.cpp]: Maybe add a comment that it's a valid situation for unit tests
