### PR TITLE
Write database minor version to disk and fix rebuild on minor version mismatch bug

### LINKED ISSUE #5822: Aleth uses genesis block as latest block when performing rebuild in response to database minor version mismatch
Even if we address #5813 and persist the minor version to disk, `BlockChain::open()` renames the extras database path on minor version mismatch: https://github.com/ethereum/aleth/blob/cd25d2f56b90a1e8fb6441343e8cd94a184ef019/libethereum/BlockChain.cpp#L213-L222

It then opens the extras DB from the old path and populates m_lastBlockHash / m_lastBlockNumber to the genesis block since the old path is empty.

Therefore the last block hash used by `BlockChain::rebuild()` to identify the range of blocks which need to be reimported will be the genesis block, and the extras (and state) databases won't actually be rebuilt.

### PR DESCRIPTION
**Pull request by halfalicious**
Fix #5822, #5813 

Built ontop of #5826 so will wait to merge this until that has been merged.

This PR fixes two bugs:
* It writes the database minor version to disk (if it's not already present such as when you launch Aleth with a new database path) - this is required to detect database minor version changes which occur during extras database upgrades (5822)
* It doesn't remove the extras or state databases on minor version mismatch (5813) - removing these databases breaks the rebuild functionality because the rebuild functionality uses the last hash to determine chain tip (and therefore the range of blocks which must be reimported) - however, `BlockChain::open` populates this after renaming extras -> extras.old so since it can't find the "best" block in the extras DB it just uses the genesis hash.

### CODE REVIEW

File: libethereum/BlockChain.cpp [hunk 1]
```diff
@@ -268,7 +276,7 @@ unsigned BlockChain::open(fs::path const& _path, WithExisting _we)
         throw;
     }
 
-    if (_we != WithExisting::Verify && !details(m_genesisHash))
+    if (_we != WithExisting::Verify && !rebuildNeeded && !details(m_genesisHash))
```
Comment (gumb0) [inline libethereum/BlockChain.cpp]: If do this insertion here in case `rebuildNeeded == true`, maybe then we don't need to duplicate this code in `rebuild` ?

Comment (gumb0) [reply libethereum/BlockChain.cpp]: Ah I see, rebuild will first rename this database anyway

**Comment by halfalicious** [comment]
Rebased
